"""Validate and attest the native GH200 Biohub reference dependency lock."""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import os
import platform
import re
import subprocess
import sys
from collections.abc import Mapping, Sequence
from dataclasses import asdict, dataclass
from pathlib import Path, PurePosixPath
from typing import Any
from urllib.parse import urlsplit


_SCHEMA_VERSION = 2
_EVIDENCE_SCHEMA_VERSION = 1
_DIGEST = re.compile(r"[0-9a-f]{64}")
_IMAGE_ID = re.compile(r"sha256:[0-9a-f]{64}")
_NAME = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*")
_PINNED = re.compile(r"(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)==(?P<version>[^\s;]+)")
_HASH_OPTION = re.compile(r"(?:^|\s)--hash=sha256:([0-9a-f]{64})(?=\s|$)")
_RUNTIME_HEADER = (
    "# This file was autogenerated by uv via the following command:",
    "#    python -m tools.remote.biohub_reference_lock generate",
)
_BUILD_HEADER = (
    "# This file was autogenerated by uv via the following command:",
    "#    python -m tools.remote.biohub_reference_lock generate-build-lock",
)
_RUNTIME_DIRECTIVES = (
    "--index-url https://pypi.org/simple",
    "--extra-index-url https://download.pytorch.org/whl/cu130",
    "--no-binary biotraj",
    "--only-binary :all:",
)
_MATERIALIZED_DIRECTIVES = (
    "--index-url https://pypi.org/simple",
    "--extra-index-url https://download.pytorch.org/whl/cu130",
    "--only-binary :all:",
)
_BUILD_DIRECTIVES = (
    "--index-url https://pypi.org/simple",
    "--only-binary :all:",
)
_BUILD_INVENTORY = {
    "cython": "3.2.4",
    "numpy": "2.4.4",
    "packaging": "26.2",
    "pip": "26.1.1",
    "setuptools": "83.0.0",
    "setuptools-scm": "9.2.2",
    "wheel": "0.47.0",
}
_RUNTIME_SENTINELS = {
    "numpy": "1.26.4",
    "pytest": "9.0.2",
    "torch": "2.13.0+cu130",
    "wheel": "0.47.0",
    "zstd": "1.5.6.1",
}


class BiohubReferenceLockError(RuntimeError):
    """The checked-in Biohub reference lock or runtime differs from its contract."""


@dataclass(frozen=True)
class TargetPolicy:
    """The one supported execution target for this reference lock."""

    hardware: str
    operating_system: str
    architecture: str
    container_platform: str
    python_implementation: str
    python_version: str
    cuda_version: str
    torch_backend: str


@dataclass(frozen=True)
class ContainerPolicy:
    """Immutable build recipe and base-image identities."""

    dockerfile_path: str
    dockerfile_sha256: str
    dockerfile_frontend: str
    cuda_image: str
    cuda_image_digest: str
    python_image: str
    python_image_digest: str
    build_python_version: str


@dataclass(frozen=True)
class LockFilePolicy:
    """One canonical input and its generated hash lock."""

    input_path: str
    input_sha256: str
    lock_path: str
    lock_sha256: str
    package_count: int


@dataclass(frozen=True)
class BioTrajPolicy:
    """Pinned BioTraj source and reproducibly built native wheel."""

    version: str
    sdist_url: str
    sdist_sha256: str
    wheel_filename: str
    wheel_sha256: str
    wheel_size: int


@dataclass(frozen=True)
class PipCheckPlatformException:
    """One exact upstream wheel-tag defect accepted by the locked runtime."""

    distribution: str
    version: str
    wheel_filename: str
    wheel_sha256: str
    filename_platform_tag: str
    wheel_metadata_platform_tag: str
    target_hardware: str
    target_operating_system: str
    target_architecture: str
    accepted_diagnostic: str
    resolution: str


@dataclass(frozen=True)
class BiohubReferenceLockContract:
    """Strict schema for the native Biohub dependency evidence boundary."""

    schema_version: int
    contract: str
    target: TargetPolicy
    container: ContainerPolicy
    runtime: LockFilePolicy
    build: LockFilePolicy
    biotraj: BioTrajPolicy
    bootstrap_inventory: Mapping[str, str]
    final_inventory_overlays: Mapping[str, str]
    pip_check_platform_exceptions: tuple[PipCheckPlatformException, ...]


@dataclass(frozen=True)
class ParsedLock:
    """Normalized inventory and hashes parsed from one requirements lock."""

    inventory: Mapping[str, str]
    hashes: Mapping[str, tuple[str, ...]]
    directives: tuple[str, ...]


def canonical_distribution_name(value: str) -> str:
    """Return the PEP 503 spelling used for inventory comparisons."""

    return re.sub(r"[-_.]+", "-", value).lower()


def normalize_distribution_version(name: str, value: str) -> str:
    """Normalize metadata spelling while retaining Torch's CUDA local version."""

    normalized = value.strip().lower().replace("_", ".").replace("-", ".")
    if canonical_distribution_name(name) != "torch":
        return normalized
    match = re.fullmatch(r"(\d+(?:\.\d+){2})(?:\+([a-z0-9.]+))?", normalized)
    if match is None:
        raise BiohubReferenceLockError(f"Invalid Torch version in inventory: {value!r}")
    local = match.group(2)
    if local in {"cu13.0", "cu130"}:
        local = "cu130"
    return match.group(1) + (f"+{local}" if local else "")


def _load_json(path: Path) -> dict[str, object]:
    try:
        raw: Any = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise BiohubReferenceLockError(f"Unable to read Biohub lock contract: {path}") from error
    if not isinstance(raw, dict) or not all(isinstance(key, str) for key in raw):
        raise BiohubReferenceLockError("Biohub lock contract must be a JSON object.")
    return {str(key): value for key, value in raw.items()}


def _exact_fields(raw: Mapping[str, object], expected: set[str], *, context: str) -> None:
    if set(raw) == expected:
        return
    raise BiohubReferenceLockError(
        f"{context} fields differ: missing={sorted(expected.difference(raw))}, "
        f"extra={sorted(set(raw).difference(expected))}."
    )


def _mapping(value: object, *, field: str) -> dict[str, object]:
    if not isinstance(value, Mapping) or not all(isinstance(key, str) for key in value):
        raise BiohubReferenceLockError(f"{field} must be a JSON object.")
    return {str(key): item for key, item in value.items()}


def _string(value: object, *, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise BiohubReferenceLockError(f"{field} must be a non-empty string.")
    return value


def _digest(value: object, *, field: str) -> str:
    digest = _string(value, field=field)
    if _DIGEST.fullmatch(digest) is None:
        raise BiohubReferenceLockError(f"{field} must be 64 lowercase hexadecimal characters.")
    return digest


def _positive_int(value: object, *, field: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise BiohubReferenceLockError(f"{field} must be a positive integer.")
    return value


def _portable_path(value: object, *, field: str) -> str:
    rendered = _string(value, field=field)
    path = PurePosixPath(rendered)
    if path.is_absolute() or ".." in path.parts or path.as_posix() != rendered:
        raise BiohubReferenceLockError(f"{field} must be a portable relative path.")
    return rendered


def _parse_target(value: object) -> TargetPolicy:
    raw = _mapping(value, field="target")
    fields = set(TargetPolicy.__dataclass_fields__)
    _exact_fields(raw, fields, context="target")
    target = TargetPolicy(
        **{field: _string(raw[field], field=f"target.{field}") for field in fields}
    )
    required = TargetPolicy(
        hardware="NVIDIA GH200 480GB",
        operating_system="linux",
        architecture="aarch64",
        container_platform="linux/arm64",
        python_implementation="CPython",
        python_version="3.12",
        cuda_version="13.0",
        torch_backend="cu130",
    )
    if target != required:
        raise BiohubReferenceLockError(f"Unsupported Biohub lock target: {target!r}")
    return target


def _parse_container(value: object) -> ContainerPolicy:
    raw = _mapping(value, field="container")
    fields = set(ContainerPolicy.__dataclass_fields__)
    _exact_fields(raw, fields, context="container")
    policy = ContainerPolicy(
        dockerfile_path=_portable_path(raw["dockerfile_path"], field="container.dockerfile_path"),
        dockerfile_sha256=_digest(raw["dockerfile_sha256"], field="container.dockerfile_sha256"),
        dockerfile_frontend=_string(
            raw["dockerfile_frontend"], field="container.dockerfile_frontend"
        ),
        cuda_image=_string(raw["cuda_image"], field="container.cuda_image"),
        cuda_image_digest=_digest(raw["cuda_image_digest"], field="container.cuda_image_digest"),
        python_image=_string(raw["python_image"], field="container.python_image"),
        python_image_digest=_digest(
            raw["python_image_digest"], field="container.python_image_digest"
        ),
        build_python_version=_string(
            raw["build_python_version"], field="container.build_python_version"
        ),
    )
    expected_frontend = (
        "docker/dockerfile:1.19@sha256:"
        "b6afd42430b15f2d2a4c5a02b919e98a525b785b1aaff16747d2f623364e39b6"
    )
    if policy.dockerfile_path != "docker/biohub-reference-lock.Dockerfile":
        raise BiohubReferenceLockError("Unexpected Biohub lock Dockerfile path.")
    if policy.dockerfile_frontend != expected_frontend:
        raise BiohubReferenceLockError("Unexpected Biohub lock Dockerfile frontend.")
    if not policy.cuda_image.endswith("@sha256:" + policy.cuda_image_digest):
        raise BiohubReferenceLockError("CUDA image does not use its declared ARM64 child digest.")
    if not policy.python_image.endswith("@sha256:" + policy.python_image_digest):
        raise BiohubReferenceLockError("Python image does not use its declared ARM64 child digest.")
    if policy.build_python_version != "3.12.11":
        raise BiohubReferenceLockError("Unexpected BioTraj build Python patch version.")
    return policy


def _parse_lock_policy(value: object, *, field: str) -> LockFilePolicy:
    raw = _mapping(value, field=field)
    fields = set(LockFilePolicy.__dataclass_fields__)
    _exact_fields(raw, fields, context=field)
    return LockFilePolicy(
        input_path=_portable_path(raw["input_path"], field=f"{field}.input_path"),
        input_sha256=_digest(raw["input_sha256"], field=f"{field}.input_sha256"),
        lock_path=_portable_path(raw["lock_path"], field=f"{field}.lock_path"),
        lock_sha256=_digest(raw["lock_sha256"], field=f"{field}.lock_sha256"),
        package_count=_positive_int(raw["package_count"], field=f"{field}.package_count"),
    )


def _parse_biotraj(value: object) -> BioTrajPolicy:
    raw = _mapping(value, field="biotraj")
    fields = set(BioTrajPolicy.__dataclass_fields__)
    _exact_fields(raw, fields, context="biotraj")
    policy = BioTrajPolicy(
        version=_string(raw["version"], field="biotraj.version"),
        sdist_url=_string(raw["sdist_url"], field="biotraj.sdist_url"),
        sdist_sha256=_digest(raw["sdist_sha256"], field="biotraj.sdist_sha256"),
        wheel_filename=_string(raw["wheel_filename"], field="biotraj.wheel_filename"),
        wheel_sha256=_digest(raw["wheel_sha256"], field="biotraj.wheel_sha256"),
        wheel_size=_positive_int(raw["wheel_size"], field="biotraj.wheel_size"),
    )
    expected_wheel = "biotraj-1.2.2-cp312-cp312-linux_aarch64.whl"
    if policy.version != "1.2.2" or policy.wheel_filename != expected_wheel:
        raise BiohubReferenceLockError("BioTraj version or native wheel tag differs.")
    parsed = urlsplit(policy.sdist_url)
    if parsed.scheme != "https" or parsed.hostname != "files.pythonhosted.org":
        raise BiohubReferenceLockError("BioTraj sdist must use the pinned Pythonhost URL.")
    if parsed.fragment != "sha256=" + policy.sdist_sha256:
        raise BiohubReferenceLockError("BioTraj sdist URL fragment differs from its digest.")
    return policy


def _parse_inventory(value: object, *, field: str) -> dict[str, str]:
    raw = _mapping(value, field=field)
    result: dict[str, str] = {}
    for raw_name, raw_version in raw.items():
        if _NAME.fullmatch(raw_name) is None:
            raise BiohubReferenceLockError(f"Invalid distribution name in {field}: {raw_name!r}")
        name = canonical_distribution_name(raw_name)
        if name != raw_name or name in result:
            raise BiohubReferenceLockError(f"{field} names must be unique and canonical.")
        result[name] = normalize_distribution_version(
            name, _string(raw_version, field=f"{field}.{name}")
        )
    return dict(sorted(result.items()))


def _parse_pip_check_platform_exceptions(
    value: object,
) -> tuple[PipCheckPlatformException, ...]:
    if not isinstance(value, list) or len(value) != 1:
        raise BiohubReferenceLockError(
            "pip_check_platform_exceptions must contain the one declared vendor defect."
        )
    raw = _mapping(value[0], field="pip_check_platform_exceptions[0]")
    fields = set(PipCheckPlatformException.__dataclass_fields__)
    _exact_fields(raw, fields, context="pip_check_platform_exceptions[0]")
    policy = PipCheckPlatformException(
        distribution=_string(
            raw["distribution"], field="pip_check_platform_exceptions[0].distribution"
        ),
        version=_string(raw["version"], field="pip_check_platform_exceptions[0].version"),
        wheel_filename=_string(
            raw["wheel_filename"], field="pip_check_platform_exceptions[0].wheel_filename"
        ),
        wheel_sha256=_digest(
            raw["wheel_sha256"], field="pip_check_platform_exceptions[0].wheel_sha256"
        ),
        filename_platform_tag=_string(
            raw["filename_platform_tag"],
            field="pip_check_platform_exceptions[0].filename_platform_tag",
        ),
        wheel_metadata_platform_tag=_string(
            raw["wheel_metadata_platform_tag"],
            field="pip_check_platform_exceptions[0].wheel_metadata_platform_tag",
        ),
        target_hardware=_string(
            raw["target_hardware"],
            field="pip_check_platform_exceptions[0].target_hardware",
        ),
        target_operating_system=_string(
            raw["target_operating_system"],
            field="pip_check_platform_exceptions[0].target_operating_system",
        ),
        target_architecture=_string(
            raw["target_architecture"],
            field="pip_check_platform_exceptions[0].target_architecture",
        ),
        accepted_diagnostic=_string(
            raw["accepted_diagnostic"],
            field="pip_check_platform_exceptions[0].accepted_diagnostic",
        ),
        resolution=_string(raw["resolution"], field="pip_check_platform_exceptions[0].resolution"),
    )
    required = PipCheckPlatformException(
        distribution="nvidia-cusparselt-cu13",
        version="0.8.1",
        wheel_filename=("nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_aarch64.whl"),
        wheel_sha256=("4dca476c50bf4780d46cd0bfbd82e2bc10a08e4fef7950917ce8d7578d22a23f"),
        filename_platform_tag="py3-none-manylinux2014_aarch64",
        wheel_metadata_platform_tag="py3-none-manylinux2014_sbsa",
        target_hardware="NVIDIA GH200 480GB",
        target_operating_system="linux",
        target_architecture="aarch64",
        accepted_diagnostic=("nvidia-cusparselt-cu13 0.8.1 is not supported on this platform"),
        resolution="validated-vendor-metadata-exception-no-wheel-rewrite",
    )
    if policy != required:
        raise BiohubReferenceLockError("Unexpected pip-check platform exception policy.")
    return (policy,)


def load_biohub_reference_lock_contract(path: Path) -> BiohubReferenceLockContract:
    """Load the checked-in strict GH200 lock contract."""

    raw = _load_json(path)
    expected = {
        "schema_version",
        "contract",
        "target",
        "container",
        "runtime",
        "build",
        "biotraj",
        "bootstrap_inventory",
        "final_inventory_overlays",
        "pip_check_platform_exceptions",
    }
    _exact_fields(raw, expected, context="contract")
    if raw["schema_version"] != _SCHEMA_VERSION:
        raise BiohubReferenceLockError("Unsupported Biohub lock contract schema version.")
    if raw["contract"] != "fastplms.biohub-reference-lock":
        raise BiohubReferenceLockError("Unexpected Biohub lock contract identifier.")
    bootstrap = _parse_inventory(raw["bootstrap_inventory"], field="bootstrap_inventory")
    final_overlays = _parse_inventory(
        raw["final_inventory_overlays"], field="final_inventory_overlays"
    )
    if bootstrap != {"pip": "26.1.1"}:
        raise BiohubReferenceLockError("Unexpected Biohub bootstrap inventory.")
    expected_final = {"esm": "3.3.0", "transformers": "4.57.6", "uv": "0.10.12"}
    if final_overlays != expected_final:
        raise BiohubReferenceLockError("Unexpected Biohub final inventory overlays.")
    contract = BiohubReferenceLockContract(
        schema_version=_SCHEMA_VERSION,
        contract="fastplms.biohub-reference-lock",
        target=_parse_target(raw["target"]),
        container=_parse_container(raw["container"]),
        runtime=_parse_lock_policy(raw["runtime"], field="runtime"),
        build=_parse_lock_policy(raw["build"], field="build"),
        biotraj=_parse_biotraj(raw["biotraj"]),
        bootstrap_inventory=bootstrap,
        final_inventory_overlays=final_overlays,
        pip_check_platform_exceptions=_parse_pip_check_platform_exceptions(
            raw["pip_check_platform_exceptions"]
        ),
    )
    if contract.runtime.package_count != 108 or contract.build.package_count != 7:
        raise BiohubReferenceLockError(
            "Biohub lock package counts must be 108 runtime and 7 build."
        )
    return contract


def _sha256(path: Path) -> str:
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()
    except OSError as error:
        raise BiohubReferenceLockError(f"Unable to hash required lock input: {path}") from error


def _contract_path(root: Path, relative: str) -> Path:
    root = root.resolve()
    path = root.joinpath(*PurePosixPath(relative).parts).resolve()
    try:
        path.relative_to(root)
    except ValueError as error:
        raise BiohubReferenceLockError(
            f"Contract path escapes repository root: {relative}"
        ) from error
    return path


def _read_lock(path: Path) -> tuple[list[str], bytes]:
    try:
        serialized = path.read_bytes()
        text = serialized.decode("utf-8")
    except (OSError, UnicodeDecodeError) as error:
        raise BiohubReferenceLockError(f"Unable to read requirements lock: {path}") from error
    if not serialized.endswith(b"\n") or b"\r" in serialized:
        raise BiohubReferenceLockError("Requirements lock must use canonical LF text ending in LF.")
    return text.splitlines(), serialized


def _logical_entries(lines: Sequence[str]) -> tuple[tuple[str, ...], tuple[str, ...]]:
    directives: list[str] = []
    entries: list[str] = []
    pending = ""
    for line in lines:
        if not line.strip():
            if pending:
                raise BiohubReferenceLockError("Blank line interrupts a lock continuation.")
            continue
        if line.startswith("#"):
            raise BiohubReferenceLockError("Unexpected comment in generated requirements body.")
        if line.startswith("--") and not pending:
            directives.append(line)
            continue
        continuation = line.rstrip().endswith("\\")
        piece = line.rstrip()[:-1].strip() if continuation else line.strip()
        pending = f"{pending} {piece}".strip()
        if not continuation:
            entries.append(pending)
            pending = ""
    if pending:
        raise BiohubReferenceLockError("Requirements lock ends during a continuation.")
    return tuple(directives), tuple(entries)


def _parse_hashed_lock(
    path: Path,
    *,
    header: tuple[str, str],
    directives: tuple[str, ...],
    biotraj_url: str | None,
    biotraj_digest: str | None,
    biotraj_version: str,
) -> ParsedLock:
    lines, _ = _read_lock(path)
    if tuple(lines[:2]) != header:
        raise BiohubReferenceLockError("Generated lock header differs from the stable command.")
    observed_directives, entries = _logical_entries(lines[2:])
    if observed_directives != directives:
        raise BiohubReferenceLockError(
            f"Generated lock directives differ: {observed_directives!r}."
        )
    inventory: dict[str, str] = {}
    hashes_by_name: dict[str, tuple[str, ...]] = {}
    observed_order: list[str] = []
    for entry in entries:
        hashes = tuple(_HASH_OPTION.findall(entry))
        requirement = _HASH_OPTION.sub("", entry).strip()
        pinned = _PINNED.fullmatch(requirement)
        if pinned is not None:
            raw_name = pinned.group("name")
            version = pinned.group("version")
        elif biotraj_url is not None and requirement == f"biotraj @ {biotraj_url}":
            raw_name = "biotraj"
            version = biotraj_version
            if hashes != (biotraj_digest,):
                raise BiohubReferenceLockError(
                    "BioTraj lock must contain only its selected digest."
                )
        else:
            raise BiohubReferenceLockError(
                f"Unpinned or unsupported lock requirement: {requirement}"
            )
        name = canonical_distribution_name(raw_name)
        if raw_name != name or name in inventory:
            raise BiohubReferenceLockError(f"Duplicate or non-canonical lock name: {raw_name!r}")
        if not hashes or tuple(sorted(set(hashes))) != hashes:
            raise BiohubReferenceLockError(f"Hashes for {name!r} must be unique and sorted.")
        inventory[name] = normalize_distribution_version(name, version)
        hashes_by_name[name] = hashes
        observed_order.append(name)
    if observed_order != sorted(observed_order):
        raise BiohubReferenceLockError("Generated lock inventory is not sorted by canonical name.")
    return ParsedLock(
        inventory=dict(sorted(inventory.items())),
        hashes=dict(sorted(hashes_by_name.items())),
        directives=observed_directives,
    )


def verify_biohub_reference_lock_contract(
    repository_root: Path,
    contract_path: Path,
) -> dict[str, object]:
    """Rehash every input and validate both generated dependency graphs."""

    contract = load_biohub_reference_lock_contract(contract_path)
    file_policies = (contract.runtime, contract.build)
    for policy in file_policies:
        for relative, expected in (
            (policy.input_path, policy.input_sha256),
            (policy.lock_path, policy.lock_sha256),
        ):
            actual = _sha256(_contract_path(repository_root, relative))
            if actual != expected:
                raise BiohubReferenceLockError(
                    f"Biohub lock file digest differs for {relative}: "
                    f"expected {expected}, received {actual}."
                )
    dockerfile = _contract_path(repository_root, contract.container.dockerfile_path)
    if _sha256(dockerfile) != contract.container.dockerfile_sha256:
        raise BiohubReferenceLockError("Biohub reference lock Dockerfile digest differs.")

    runtime_lock = _parse_hashed_lock(
        _contract_path(repository_root, contract.runtime.lock_path),
        header=_RUNTIME_HEADER,
        directives=_RUNTIME_DIRECTIVES,
        biotraj_url=contract.biotraj.sdist_url,
        biotraj_digest=contract.biotraj.sdist_sha256,
        biotraj_version=contract.biotraj.version,
    )
    build_lock = _parse_hashed_lock(
        _contract_path(repository_root, contract.build.lock_path),
        header=_BUILD_HEADER,
        directives=_BUILD_DIRECTIVES,
        biotraj_url=None,
        biotraj_digest=None,
        biotraj_version=contract.biotraj.version,
    )
    if len(runtime_lock.inventory) != contract.runtime.package_count:
        raise BiohubReferenceLockError("Runtime dependency graph package count differs.")
    if len(build_lock.inventory) != contract.build.package_count:
        raise BiohubReferenceLockError("BioTraj build graph package count differs.")
    if dict(build_lock.inventory) != _BUILD_INVENTORY:
        raise BiohubReferenceLockError("BioTraj PEP 517 build toolchain differs.")
    for name, expected in _RUNTIME_SENTINELS.items():
        if runtime_lock.inventory.get(name) != expected:
            raise BiohubReferenceLockError(
                f"Runtime lock sentinel {name!r} differs from {expected!r}."
            )
    if runtime_lock.inventory.get("biotraj") != contract.biotraj.version:
        raise BiohubReferenceLockError("Runtime BioTraj version differs from source contract.")
    for exception in contract.pip_check_platform_exceptions:
        if runtime_lock.inventory.get(exception.distribution) != exception.version:
            raise BiohubReferenceLockError(
                "Pip-check exception distribution differs from the runtime lock."
            )
        if exception.wheel_sha256 not in runtime_lock.hashes.get(exception.distribution, ()):
            raise BiohubReferenceLockError(
                "Pip-check exception wheel digest is absent from the runtime lock."
            )
    forbidden = {"esm", "pip", "transformers", "uv"}.intersection(runtime_lock.inventory)
    if forbidden:
        raise BiohubReferenceLockError(
            f"Source/bootstrap overlays leaked into runtime dependency graph: {sorted(forbidden)}"
        )
    return {
        "schema_version": _SCHEMA_VERSION,
        "target": asdict(contract.target),
        "runtime_lock_sha256": contract.runtime.lock_sha256,
        "runtime_package_count": len(runtime_lock.inventory),
        "build_lock_sha256": contract.build.lock_sha256,
        "build_package_count": len(build_lock.inventory),
        "biotraj_sdist_sha256": contract.biotraj.sdist_sha256,
        "biotraj_wheel_sha256": contract.biotraj.wheel_sha256,
        "pip_check_platform_exceptions": [
            asdict(exception) for exception in contract.pip_check_platform_exceptions
        ],
    }


def expected_installed_inventory(
    repository_root: Path,
    contract_path: Path,
    *,
    profile: str,
) -> dict[str, str]:
    """Return the exact expected distributions for one build/runtime phase."""

    contract = load_biohub_reference_lock_contract(contract_path)
    verify_biohub_reference_lock_contract(repository_root, contract_path)
    if profile == "build":
        return dict(_BUILD_INVENTORY)
    runtime_lock = _parse_hashed_lock(
        _contract_path(repository_root, contract.runtime.lock_path),
        header=_RUNTIME_HEADER,
        directives=_RUNTIME_DIRECTIVES,
        biotraj_url=contract.biotraj.sdist_url,
        biotraj_digest=contract.biotraj.sdist_sha256,
        biotraj_version=contract.biotraj.version,
    )
    expected = dict(runtime_lock.inventory)
    if profile not in {"runtime", "final"}:
        raise BiohubReferenceLockError(f"Unsupported installed-inventory profile: {profile!r}")
    for name, version in contract.bootstrap_inventory.items():
        if name in expected:
            raise BiohubReferenceLockError(f"Bootstrap inventory collides with lock: {name}")
        expected[name] = version
    if profile == "final":
        for name, version in contract.final_inventory_overlays.items():
            if name in expected:
                raise BiohubReferenceLockError(
                    f"Final inventory overlay collides with lock: {name}"
                )
            expected[name] = version
    return dict(sorted(expected.items()))


def installed_distribution_inventory() -> dict[str, str]:
    """Collect the current interpreter's exact normalized distribution inventory."""

    inventory: dict[str, str] = {}
    for distribution in importlib.metadata.distributions():
        raw_name = distribution.metadata.get("Name")
        if not isinstance(raw_name, str) or not raw_name:
            raise BiohubReferenceLockError("Installed distribution has no Name metadata.")
        name = canonical_distribution_name(raw_name)
        version = normalize_distribution_version(name, distribution.version)
        if name in inventory:
            raise BiohubReferenceLockError(f"Duplicate installed distribution metadata: {name}")
        inventory[name] = version
    return dict(sorted(inventory.items()))


def assert_exact_installed_inventory(
    expected: Mapping[str, str],
    observed: Mapping[str, str],
) -> dict[str, str]:
    """Fail closed on a missing, extra, or version-divergent distribution."""

    normalized_observed: dict[str, str] = {}
    for raw_name, raw_version in observed.items():
        name = canonical_distribution_name(raw_name)
        if name in normalized_observed:
            raise BiohubReferenceLockError(f"Observed inventory contains duplicate name: {name}")
        normalized_observed[name] = normalize_distribution_version(name, raw_version)
    normalized_expected = {
        canonical_distribution_name(name): normalize_distribution_version(name, version)
        for name, version in expected.items()
    }
    missing = sorted(set(normalized_expected).difference(normalized_observed))
    extra = sorted(set(normalized_observed).difference(normalized_expected))
    changed = {
        name: {
            "expected": normalized_expected[name],
            "observed": normalized_observed[name],
        }
        for name in sorted(set(normalized_expected).intersection(normalized_observed))
        if normalized_expected[name] != normalized_observed[name]
    }
    if missing or extra or changed:
        raise BiohubReferenceLockError(
            "Installed distribution inventory differs: "
            f"missing={missing}, extra={extra}, changed={changed}."
        )
    return dict(sorted(normalized_observed.items()))


def verify_current_installed_inventory(
    repository_root: Path,
    contract_path: Path,
    *,
    profile: str,
) -> dict[str, str]:
    """Verify the current Python environment against one exact lock profile."""

    expected = expected_installed_inventory(repository_root, contract_path, profile=profile)
    return assert_exact_installed_inventory(expected, installed_distribution_inventory())


def verify_current_pip_check(
    repository_root: Path,
    contract_path: Path,
) -> dict[str, object]:
    """Run pip check while accepting only the attested NVIDIA SBSA tag defect."""

    contract = load_biohub_reference_lock_contract(contract_path)
    verify_biohub_reference_lock_contract(repository_root, contract_path)
    verify_current_installed_inventory(repository_root, contract_path, profile="final")
    if (
        platform.system().lower() != contract.target.operating_system
        or platform.machine() != contract.target.architecture
    ):
        raise BiohubReferenceLockError(
            "Pip-check platform exception is valid only on locked Linux/aarch64."
        )
    exception = contract.pip_check_platform_exceptions[0]
    if (
        exception.target_hardware != contract.target.hardware
        or exception.target_operating_system != contract.target.operating_system
        or exception.target_architecture != contract.target.architecture
    ):
        raise BiohubReferenceLockError(
            "Pip-check platform exception target differs from the lock target."
        )
    try:
        distribution = importlib.metadata.distribution(exception.distribution)
        wheel_metadata = distribution.read_text("WHEEL")
    except (importlib.metadata.PackageNotFoundError, OSError) as error:
        raise BiohubReferenceLockError(
            "Unable to inspect the accepted pip-check exception distribution."
        ) from error
    if wheel_metadata is None:
        raise BiohubReferenceLockError(
            "Accepted pip-check exception distribution has no WHEEL metadata."
        )
    wheel_tags = tuple(
        line.removeprefix("Tag: ").strip()
        for line in wheel_metadata.splitlines()
        if line.startswith("Tag: ")
    )
    if wheel_tags != (exception.wheel_metadata_platform_tag,):
        raise BiohubReferenceLockError(
            "NVIDIA cuSPARSELt WHEEL tag differs from the accepted vendor defect."
        )
    try:
        completed = subprocess.run(
            [sys.executable, "-m", "pip", "check"],
            check=False,
            capture_output=True,
            text=True,
            timeout=60,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise BiohubReferenceLockError("Unable to execute pip check.") from error
    diagnostics = tuple(
        line.strip()
        for stream in (completed.stdout, completed.stderr)
        for line in stream.splitlines()
        if line.strip()
    )
    if completed.returncode != 1 or diagnostics != (exception.accepted_diagnostic,):
        raise BiohubReferenceLockError(
            "Pip check differs from the one accepted NVIDIA wheel-tag diagnostic: "
            f"returncode={completed.returncode}, diagnostics={diagnostics!r}."
        )
    return {
        "status": "accepted-platform-exception",
        "returncode": completed.returncode,
        "diagnostics": list(diagnostics),
        "accepted_platform_exceptions": [asdict(exception)],
    }


def _atomic_write(path: Path, payload: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_bytes(payload)
    temporary.replace(path)


def materialize_biotraj_wheel_lock(
    repository_root: Path,
    contract_path: Path,
    wheel: Path,
    output: Path,
    *,
    wheel_uri: str,
) -> ParsedLock:
    """Replace the attested BioTraj sdist with its attested native wheel."""

    contract = load_biohub_reference_lock_contract(contract_path)
    verify_biohub_reference_lock_contract(repository_root, contract_path)
    if wheel.name != contract.biotraj.wheel_filename:
        raise BiohubReferenceLockError("BioTraj wheel filename differs from native target tag.")
    if wheel.stat().st_size != contract.biotraj.wheel_size:
        raise BiohubReferenceLockError("BioTraj wheel size differs from deterministic build.")
    if _sha256(wheel) != contract.biotraj.wheel_sha256:
        raise BiohubReferenceLockError("BioTraj wheel digest differs from deterministic build.")
    parsed_uri = urlsplit(wheel_uri)
    if (
        parsed_uri.scheme != "file"
        or parsed_uri.netloc
        or parsed_uri.query
        or parsed_uri.fragment
        or PurePosixPath(parsed_uri.path).name != contract.biotraj.wheel_filename
    ):
        raise BiohubReferenceLockError("Materialized BioTraj wheel URI is not an exact file URI.")

    lock_path = _contract_path(repository_root, contract.runtime.lock_path)
    lines, _ = _read_lock(lock_path)
    rendered: list[str] = []
    replaced = False
    index = 0
    while index < len(lines):
        line = lines[index]
        if line == "--no-binary biotraj":
            index += 1
            continue
        if line.startswith("biotraj @ "):
            if replaced:
                raise BiohubReferenceLockError("Runtime lock contains duplicate BioTraj entries.")
            while line.rstrip().endswith("\\"):
                index += 1
                if index >= len(lines):
                    raise BiohubReferenceLockError("BioTraj lock entry ends during continuation.")
                line = lines[index]
            rendered.extend(
                (
                    f"biotraj @ {wheel_uri} \\",
                    f"    --hash=sha256:{contract.biotraj.wheel_sha256}",
                )
            )
            replaced = True
            index += 1
            continue
        rendered.append(line)
        index += 1
    if not replaced:
        raise BiohubReferenceLockError("Runtime lock contains no BioTraj source entry.")
    _atomic_write(output, ("\n".join(rendered) + "\n").encode())
    materialized = _parse_hashed_lock(
        output,
        header=_RUNTIME_HEADER,
        directives=_MATERIALIZED_DIRECTIVES,
        biotraj_url=wheel_uri,
        biotraj_digest=contract.biotraj.wheel_sha256,
        biotraj_version=contract.biotraj.version,
    )
    if len(materialized.inventory) != contract.runtime.package_count:
        raise BiohubReferenceLockError("Materialized runtime lock package count differs.")
    return materialized


def _first_command_line(command: Sequence[str]) -> str:
    try:
        completed = subprocess.run(
            command,
            check=True,
            capture_output=True,
            text=True,
            timeout=15,
        )
    except (OSError, subprocess.CalledProcessError, subprocess.TimeoutExpired) as error:
        raise BiohubReferenceLockError(
            f"Unable to attest toolchain command: {command!r}"
        ) from error
    lines = completed.stdout.splitlines()
    if not lines:
        raise BiohubReferenceLockError(f"Toolchain command emitted no version: {command!r}")
    return lines[0]


def _gpu_name() -> str:
    try:
        completed = subprocess.run(
            ["nvidia-smi", "--query-gpu=name", "--format=csv,noheader"],
            check=True,
            capture_output=True,
            text=True,
            timeout=15,
        )
    except (OSError, subprocess.CalledProcessError, subprocess.TimeoutExpired) as error:
        raise BiohubReferenceLockError("Unable to attest the GH200 build host.") from error
    names = tuple(line.strip() for line in completed.stdout.splitlines() if line.strip())
    if len(names) != 1:
        raise BiohubReferenceLockError(f"Expected one GH200 device, received {names!r}.")
    return names[0]


def write_biohub_reference_build_evidence(
    repository_root: Path,
    contract_path: Path,
    wheel: Path,
    output: Path,
    *,
    build_image_id: str,
) -> dict[str, object]:
    """Write native image, toolchain, wheel, and build-inventory evidence."""

    contract = load_biohub_reference_lock_contract(contract_path)
    lock_evidence = verify_biohub_reference_lock_contract(repository_root, contract_path)
    if _IMAGE_ID.fullmatch(build_image_id) is None:
        raise BiohubReferenceLockError("Build image identity must be a sha256 Docker image ID.")
    if platform.system().lower() != contract.target.operating_system:
        raise BiohubReferenceLockError("Build operating system differs from lock target.")
    if platform.machine() != contract.target.architecture:
        raise BiohubReferenceLockError("Build architecture differs from lock target.")
    if platform.python_implementation() != contract.target.python_implementation:
        raise BiohubReferenceLockError("Build Python implementation differs from lock target.")
    python_version = platform.python_version()
    if python_version != contract.container.build_python_version:
        raise BiohubReferenceLockError("Build Python patch version differs from pinned image.")
    hardware = _gpu_name()
    if hardware != contract.target.hardware:
        raise BiohubReferenceLockError(
            f"Build hardware differs: expected {contract.target.hardware!r}, received {hardware!r}."
        )
    if wheel.name != contract.biotraj.wheel_filename:
        raise BiohubReferenceLockError("Evidence wheel filename differs from contract.")
    if wheel.stat().st_size != contract.biotraj.wheel_size:
        raise BiohubReferenceLockError("Evidence wheel size differs from contract.")
    if _sha256(wheel) != contract.biotraj.wheel_sha256:
        raise BiohubReferenceLockError("Evidence wheel digest differs from contract.")
    inventory = verify_current_installed_inventory(repository_root, contract_path, profile="build")
    payload: dict[str, object] = {
        "schema_version": _EVIDENCE_SCHEMA_VERSION,
        "contract_sha256": _sha256(contract_path),
        "target": asdict(contract.target),
        "container": {
            **asdict(contract.container),
            "build_image_id": build_image_id,
        },
        "observed": {
            "hardware": hardware,
            "operating_system": platform.system().lower(),
            "architecture": platform.machine(),
            "python_implementation": platform.python_implementation(),
            "python_version": python_version,
            "gcc": _first_command_line(("gcc", "--version")),
            "binutils": _first_command_line(("ld", "--version")),
        },
        "locks": lock_evidence,
        "biotraj": {
            **asdict(contract.biotraj),
            "observed_wheel_sha256": _sha256(wheel),
            "observed_wheel_size": wheel.stat().st_size,
        },
        "installed_build_inventory": inventory,
    }
    _atomic_write(output, (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode())
    return payload


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    verify = subparsers.add_parser("verify-contract")
    verify.add_argument("--root", type=Path, required=True)
    verify.add_argument("--contract", type=Path, required=True)
    inventory = subparsers.add_parser("verify-inventory")
    inventory.add_argument("--root", type=Path, required=True)
    inventory.add_argument("--contract", type=Path, required=True)
    inventory.add_argument("--profile", choices=("build", "runtime", "final"), required=True)
    pip_check = subparsers.add_parser("verify-pip-check")
    pip_check.add_argument("--root", type=Path, required=True)
    pip_check.add_argument("--contract", type=Path, required=True)
    materialize = subparsers.add_parser("materialize-wheel-lock")
    materialize.add_argument("--root", type=Path, required=True)
    materialize.add_argument("--contract", type=Path, required=True)
    materialize.add_argument("--wheel", type=Path, required=True)
    materialize.add_argument("--wheel-uri", required=True)
    materialize.add_argument("--output", type=Path, required=True)
    evidence = subparsers.add_parser("write-build-evidence")
    evidence.add_argument("--root", type=Path, required=True)
    evidence.add_argument("--contract", type=Path, required=True)
    evidence.add_argument("--wheel", type=Path, required=True)
    evidence.add_argument(
        "--build-image-id",
        default=os.environ.get("FASTPLMS_BUILD_IMAGE_ID"),
        required="FASTPLMS_BUILD_IMAGE_ID" not in os.environ,
    )
    evidence.add_argument("--output", type=Path, required=True)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Validate the lock, materialize its wheel, or write native build evidence."""

    arguments = _parser().parse_args(argv)
    if arguments.command == "verify-contract":
        result: object = verify_biohub_reference_lock_contract(arguments.root, arguments.contract)
    elif arguments.command == "verify-inventory":
        result = verify_current_installed_inventory(
            arguments.root, arguments.contract, profile=arguments.profile
        )
    elif arguments.command == "verify-pip-check":
        result = verify_current_pip_check(arguments.root, arguments.contract)
    elif arguments.command == "materialize-wheel-lock":
        parsed = materialize_biotraj_wheel_lock(
            arguments.root,
            arguments.contract,
            arguments.wheel,
            arguments.output,
            wheel_uri=arguments.wheel_uri,
        )
        result = {"package_count": len(parsed.inventory), "output": str(arguments.output)}
    else:
        result = write_biohub_reference_build_evidence(
            arguments.root,
            arguments.contract,
            arguments.wheel,
            arguments.output,
            build_image_id=arguments.build_image_id,
        )
    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
